//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SECEntities : DbContext
    {
        private static SECEntities context;
        public SECEntities()
            : base("name=SECEntities")
        {
        }

        public static SECEntities GetContext() {
            if (context==null) {
                context = new SECEntities();
            }
            return context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<energy_indicator> energy_indicator { get; set; }
        public virtual DbSet<house> house { get; set; }
        public virtual DbSet<operational_indicator> operational_indicator { get; set; }
        public virtual DbSet<organization> organization { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
