//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class operational_indicator
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public double minConsReq { get; set; }
        public double estimCons { get; set; }
        public int id_house { get; set; }
    
        public virtual house house { get; set; }
    }
}
