//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursach.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronimyc { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string post { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int id_organization { get; set; }
    
        public virtual organization organization { get; set; }
    }
}
